name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.1

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      # 1. test that the versions specified in composer.lock pass
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: vendor/bin/phpunit

      # 2. test that the version constraints in composer.json are correct
      #    (don't allow versions lower than actually supported)
      - name: Install dependencies - lowest versions allowed by constraints in composer.json
        run: composer update --prefer-lowest
      - name: Run tests
        run: vendor/bin/phpunit
